package com.laytonsmith.abstraction.enums;

import com.laytonsmith.annotations.MEnum;

@MEnum("com.commandhelper.Attribute")
public enum MCAttribute {
	GENERIC_ARMOR,
	GENERIC_ARMOR_TOUGHNESS,
	GENERIC_ATTACK_DAMAGE,
	GENERIC_ATTACK_KNOCKBACK,
	GENERIC_ATTACK_SPEED,
	GENERIC_FALL_DAMAGE_MULTIPLIER,
	GENERIC_FLYING_SPEED,
	GENERIC_FOLLOW_RANGE,
	GENERIC_GRAVITY,
	GENERIC_JUMP_STRENGTH,
	GENERIC_KNOCKBACK_RESISTANCE,
	GENERIC_LUCK,
	GENERIC_MAX_ABSORPTION,
	GENERIC_MAX_HEALTH,
	GENERIC_MOVEMENT_SPEED,
	GENERIC_SAFE_FALL_DISTANCE,
	GENERIC_SCALE,
	GENERIC_STEP_HEIGHT,
	HORSE_JUMP_STRENGTH, // changed to GENERIC_JUMP_STRENGTH
	PLAYER_BLOCK_BREAK_SPEED,
	PLAYER_BLOCK_INTERACTION_RANGE,
	PLAYER_ENTITY_INTERACTION_RANGE,
	ZOMBIE_SPAWN_REINFORCEMENTS
}
