package com.laytonsmith.abstraction.enums;

import com.laytonsmith.annotations.MEnum;

@MEnum("com.commandhelper.Effect")
public enum MCEffect {
	/**
	 * VISUAL
	 */
	DRAGON_BREATH,
	END_GATEWAY_SPAWN,
	ENDER_SIGNAL,
	INSTANT_POTION_BREAK,
	MOBSPAWNER_FLAMES,
	POTION_BREAK,
	SMOKE,
	VILLAGER_PLANT_GROW,
	/**
	 * SOUND
	 */
	ANVIL_BREAK,
	ANVIL_LAND,
	ANVIL_USE,
	BAT_TAKEOFF,
	BLAZE_SHOOT,
	BOW_FIRE,
	BREWING_STAND_BREW,
	CHORUS_FLOWER_DEATH,
	CHORUS_FLOWER_GROW,
	CLICK1,
	CLICK2,
	DOOR_CLOSE,
	DOOR_TOGGLE,
	ENDERDRAGON_GROWL,
	ENDERDRAGON_SHOOT,
	ENDEREYE_LAUNCH,
	EXTINGUISH,
	FENCE_GATE_CLOSE,
	FENCE_GATE_TOGGLE,
	FIREWORK_SHOOT,
	GHAST_SHOOT,
	GHAST_SHRIEK,
	IRON_DOOR_CLOSE,
	IRON_DOOR_TOGGLE,
	IRON_TRAPDOOR_CLOSE,
	IRON_TRAPDOOR_TOGGLE,
	PORTAL_TRAVEL,
	RECORD_PLAY,
	STEP_SOUND,
	TRAPDOOR_CLOSE,
	TRAPDOOR_TOGGLE,
	ZOMBIE_CHEW_WOODEN_DOOR,
	ZOMBIE_CHEW_IRON_DOOR,
	ZOMBIE_DESTROY_DOOR,
	WITHER_BREAK_BLOCK,
	WITHER_SHOOT,
	ZOMBIE_CONVERTED_VILLAGER,
	ZOMBIE_INFECT
}
