package com.laytonsmith.abstraction.enums;

import com.laytonsmith.annotations.MEnum;

@MEnum("EntityEffect")
public enum MCEntityEffect {
	ARROW_PARTICLES,
	RABBIT_JUMP,
	DEATH,
	HURT,
	SHEEP_EAT,
	WOLF_HEARTS,
	WOLF_SHAKE,
	WOLF_SMOKE,
	IRON_GOLEM_ROSE,
	VILLAGER_HEART,
	VILLAGER_ANGRY,
	VILLAGER_HAPPY,
	WITCH_MAGIC,
	ZOMBIE_TRANSFORM,
	FIREWORK_EXPLODE,
	LOVE_HEARTS,
	SQUID_ROTATE,
	ENTITY_POOF,
	GUARDIAN_TARGET,
	SHIELD_BLOCK,
	SHIELD_BREAK,
	ARMOR_STAND_HIT,
	THORNS_HURT,
	IRON_GOLEM_SHEATH,
	TOTEM_RESURRECT,
	HURT_DROWN,
	HURT_EXPLOSION
}
