package com.laytonsmith.abstraction.enums;

import com.laytonsmith.annotations.MEnum;

@MEnum("com.commandhelper.PlayerStatistic")
public enum MCPlayerStatistic {
	DAMAGE_DEALT,
	DAMAGE_TAKEN,
	DEATHS,
	MOB_KILLS,
	PLAYER_KILLS,
	FISH_CAUGHT,
	ANIMALS_BRED,
	LEAVE_GAME,
	JUMP,
	DROP_COUNT,
	DROP(Type.ITEM),
	PICKUP(Type.ITEM),
	PLAY_ONE_MINUTE,
	WALK_ONE_CM,
	WALK_ON_WATER_ONE_CM,
	FALL_ONE_CM,
	SNEAK_TIME,
	CLIMB_ONE_CM,
	FLY_ONE_CM,
	WALK_UNDER_WATER_ONE_CM,
	MINECART_ONE_CM,
	BOAT_ONE_CM,
	PIG_ONE_CM,
	HORSE_ONE_CM,
	SPRINT_ONE_CM,
	CROUCH_ONE_CM,
	AVIATE_ONE_CM,
	MINE_BLOCK(Type.BLOCK),
	USE_ITEM(Type.ITEM),
	BREAK_ITEM(Type.ITEM),
	CRAFT_ITEM(Type.ITEM),
	KILL_ENTITY(Type.ENTITY),
	ENTITY_KILLED_BY(Type.ENTITY),
	TIME_SINCE_DEATH,
	TALKED_TO_VILLAGER,
	TRADED_WITH_VILLAGER,
	CAKE_SLICES_EATEN,
	CAULDRON_FILLED,
	CAULDRON_USED,
	ARMOR_CLEANED,
	BANNER_CLEANED,
	BREWINGSTAND_INTERACTION,
	BEACON_INTERACTION,
	DROPPER_INSPECTED,
	HOPPER_INSPECTED,
	DISPENSER_INSPECTED,
	NOTEBLOCK_PLAYED,
	NOTEBLOCK_TUNED,
	FLOWER_POTTED,
	TRAPPED_CHEST_TRIGGERED,
	ENDERCHEST_OPENED,
	ITEM_ENCHANTED,
	RECORD_PLAYED,
	FURNACE_INTERACTION,
	CRAFTING_TABLE_INTERACTION,
	CHEST_OPENED,
	SLEEP_IN_BED,
	SHULKER_BOX_OPENED,
	TIME_SINCE_REST,
	SWIM_ONE_CM,
	DAMAGE_DEALT_ABSORBED,
	DAMAGE_DEALT_RESISTED,
	DAMAGE_BLOCKED_BY_SHIELD,
	DAMAGE_ABSORBED,
	DAMAGE_RESISTED,
	CLEAN_SHULKER_BOX,
	OPEN_BARREL,
	INTERACT_WITH_BLAST_FURNACE,
	INTERACT_WITH_SMOKER,
	INTERACT_WITH_LECTERN,
	INTERACT_WITH_CAMPFIRE,
	INTERACT_WITH_CARTOGRAPHY_TABLE,
	INTERACT_WITH_LOOM,
	INTERACT_WITH_STONECUTTER,
	BELL_RING,
	RAID_TRIGGER,
	RAID_WIN;

	private final Type type;

	MCPlayerStatistic() {
		this.type = Type.NONE;
	}

	MCPlayerStatistic(Type type) {
		this.type = type;
	}

	public Type getType() {
		return type;
	}

	public enum Type {
		BLOCK,
		ENTITY,
		ITEM,
		NONE
	}
}
