
# This is the openapi spec for apps.methodscript.com. If you make changes to this file, you must 
# regenerate the API code using the update-apps-api.cmd script at the root of the project (cross platform script).
# To keep diffs to a minimum, changes to this file MUST be contained to its own pull request.
# The OpenAPI 3.0.3 reference can be found here https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md
# It is much easier to edit this file if you use the Swagger Editor. Clone the project
# https://github.com/swagger-api/swagger-editor install node/npm, and run
# `npm start` in the directory. Copy this file into the editor, edit it, then copy it back in here when finished.
# Please do not accidentally delete this header.

openapi: 3.0.3
info:
  description: >-
    This is the api for the apps.methodscript.com server. This provides various
    public functionality for users of the MethodScript programming language.
  version: 1.0.0
  title: MethodScript Apps
  termsOfService: apps.methodscript.com/terms
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
tags:
  - name: meta
    description: Service related calls
    externalDocs:
      description: Find out more
      url: 'https://methodscript.com'
  - name: telemetry
    description: Telemetry related services
paths:
  /:
    get:
      tags:
        - meta
      summary: List services on this server
      description: >-
        Lists the services that are available on this server. In general,
        clients must load this page first to determine supported services, and
        ensure that graceful fallbacks are provided if expected services are
        missing.
      responses:
        '200':
          description: This call should always be successful.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /ping:
    description: Pings the server to check its status.
    get:
      tags:
        - meta
      summary: Pings the server to check its status
      responses:
        '200':
          description: This call should always be successful.
          content:
            text/plain:
              schema:
                type: string
  /telemetry:
    description: Obtains a telemetry key, which is used for future requests
    get:
      tags:
        - telemetry
      summary: Obtains a telemetry key, which is used for future requests
      responses:
        '200':
          description: >-
            Unless the client has been blocked, this call will always be
            successful.
          content:
            text/plain:
              schema:
                type: string
        '403':
          description: >-
            If this client has been blocked, this will not return a key.
  /telemetry/{key}:
    description: Submits a telemetry event
    post:
      tags:
        - telemetry
      summary: Submits a telemetry event.
      description: >-
        Submits a telemetry event, which is forwarded to the Application Insights
        application.
      parameters:
        - name: key
          in: path
          schema:
            type: string
          required: true
          description: The previously obtained key
      requestBody:
        required: true
        description: >-
          The telemetry event. The content should be text/plain, even though it
          will actually be json, as server merely forwards the content on to
          ApplicationInsights.
        content:
          text/plain:
            schema:
              type: string
      responses:
        '200':
          description: If the payload was successfully forwarded.
        '403':
          description: >-
            If the key was rejected. This can happen for a number of reasons,
            including things like server restart or key expiry. In any case, simply re-request
            a new key and try again. It can also happen if the server detects you're trying to
            do bad things.
        '502':
          description: >-
            If the submission was successful, but Application Insights rejected
            or otherwise unsuccessfully processed the request.
            
          
      
externalDocs:
  description: Find out more about MethodScript
  url: 'https://methodscript.com'
servers:
  - url: 'http://localhost:8080'
    variables: {}
    description: Test localhost server
  - url: 'https://apps.methodscript.com'
    variables: {}
    description: The primary apps.methodscript.com server
