/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.laytonsmith.aliasengine.events;

/**
 *
 * @author layton
 */
public enum Type {
    PLAYER_JOIN, PLAYER_LOGIN, PLAYER_PRELOGIN, PLAYER_RESPAWN, PLAYER_KICK, PLAYER_CHAT, PLAYER_COMMAND_PREPROCESS, PLAYER_QUIT, PLAYER_MOVE, PLAYER_VELOCITY, PLAYER_ANIMATION, PLAYER_TOGGLE_SNEAK, PLAYER_TOGGLE_SPRINT, PLAYER_INTERACT, PLAYER_INTERACT_ENTITY, PLAYER_EGG_THROW, PLAYER_TELEPORT, PLAYER_PORTAL, PLAYER_ITEM_HELD, PLAYER_DROP_ITEM, PLAYER_PICKUP_ITEM, PLAYER_BUCKET_EMPTY, PLAYER_BUCKET_FILL, PLAYER_INVENTORY, PLAYER_BED_ENTER, PLAYER_BED_LEAVE, PLAYER_FISH, PLAYER_GAME_MODE_CHANGE, PLAYER_CHANGED_WORLD, BLOCK_DAMAGE, BLOCK_CANBUILD, BLOCK_FROMTO, BLOCK_IGNITE, BLOCK_PHYSICS, BLOCK_PLACE, BLOCK_DISPENSE, BLOCK_BURN, LEAVES_DECAY, SIGN_CHANGE, REDSTONE_CHANGE, BLOCK_BREAK, BLOCK_FORM, BLOCK_SPREAD, BLOCK_FADE, BLOCK_PISTON_EXTEND, BLOCK_PISTON_RETRACT, INVENTORY_OPEN, INVENTORY_CLOSE, INVENTORY_CLICK, INVENTORY_CHANGE, INVENTORY_TRANSACTION, FURNACE_SMELT, FURNACE_BURN, PLUGIN_ENABLE, PLUGIN_DISABLE, SERVER_COMMAND, REMOTE_COMMAND, MAP_INITIALIZE, SERVER_LIST_PING, CHUNK_LOAD, CHUNK_UNLOAD, CHUNK_POPULATED, ITEM_SPAWN, SPAWN_CHANGE, WORLD_SAVE, WORLD_INIT, WORLD_LOAD, WORLD_UNLOAD, PORTAL_CREATE, STRUCTURE_GROW, PAINTING_PLACE, PAINTING_BREAK, ENTITY_PORTAL_ENTER, CREATURE_SPAWN, ENTITY_DAMAGE, ENTITY_DEATH, ENTITY_COMBUST, ENTITY_EXPLODE, EXPLOSION_PRIME, ENTITY_TARGET, ENTITY_INTERACT, CREEPER_POWER, PIG_ZAP, ENTITY_TAME, PROJECTILE_HIT, SLIME_SPLIT, ENTITY_REGAIN_HEALTH, ENDERMAN_PICKUP, ENDERMAN_PLACE, FOOD_LEVEL_CHANGE, LIGHTNING_STRIKE, WEATHER_CHANGE, THUNDER_CHANGE, VEHICLE_CREATE, VEHICLE_DESTROY, VEHICLE_DAMAGE, VEHICLE_COLLISION_ENTITY, VEHICLE_COLLISION_BLOCK, VEHICLE_ENTER, VEHICLE_EXIT, VEHICLE_MOVE, VEHICLE_UPDATE, CUSTOM_EVENT
}
