package com.laytonsmith.tools.docgen.localization;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

/**
 *
 */
public class AzureKeyInputDialog extends javax.swing.JDialog {


	public static interface AzureKeyInputDialogCallback {
		void getResults(String endpoint, String key, boolean storeValue);
	}

	/**
	 * Creates new form AzureKeyInputDialog
	 * @param parent The parent frame
	 * @param endpoint The existing endpoint, if any
	 * @param callback The callback is called with the key and store value setting if the user clicks ok
	 */
	public AzureKeyInputDialog(java.awt.Frame parent, String endpoint, AzureKeyInputDialogCallback callback) {
		super(parent, true);
		if(endpoint == null) {
			endpoint = "";
		}
		initComponents();
		endpointField.setText(endpoint);
		keyField.setText("");
		okButton.setEnabled(false);
		storeKeyCheckbox.setSelected(false);
		cancelButton.addActionListener((ae) -> {
			AzureKeyInputDialog.this.setVisible(false);
			this.dispose();
		});
		okButton.addActionListener((ae) -> {
			callback.getResults(endpointField.getText(), new String(keyField.getPassword()),
					storeKeyCheckbox.isSelected());
			setVisible(false);
			this.dispose();
		});
		endpointField.addKeyListener(validationListener);
		keyField.addKeyListener(validationListener);
	}

	KeyListener validationListener = new KeyListener() {
		@Override
		public void keyTyped(KeyEvent e) {
			validateInput();
		}

		@Override
		public void keyPressed(KeyEvent e) {
			validateInput();
		}

		@Override
		public void keyReleased(KeyEvent e) {
			validateInput();
		}
	};

	private void validateInput() {
		if(endpointField.getText().trim().isEmpty() || keyField.getPassword().length == 0) {
			okButton.setEnabled(false);
		} else {
			okButton.setEnabled(true);
		}
	}



	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
	 * content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        storeKeyCheckbox = new javax.swing.JCheckBox();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        endpointField = new javax.swing.JTextField();
        keyField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Input Azure Cognitive Services Key");

        storeKeyCheckbox.setText("Store Key (key is stored locally in plain text!)");

        okButton.setText("Ok");

        cancelButton.setText("Cancel");

        jLabel2.setText("Input Azure Cognitive Services Endpoint");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(endpointField)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(storeKeyCheckbox)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(okButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelButton))
                            .addComponent(jLabel2))
                        .addGap(0, 250, Short.MAX_VALUE))
                    .addComponent(keyField))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(endpointField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(keyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(storeKeyCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField endpointField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField keyField;
    private javax.swing.JButton okButton;
    private javax.swing.JCheckBox storeKeyCheckbox;
    // End of variables declaration//GEN-END:variables
}
